.TH powerkitd 8 "PowerKit Documentation"
.SH NAME
powerkitd \- PowerKit Daemon
.SH SYNOPSIS
.B powerkitd
.SH "DESCRIPTION"
.PP
\fIpowerkitd\fR
provides the
\fIorg\&.freedesktop\&.PowerKit\fR
service on the system message bus\&. Users or administrators should never need to start this daemon as it will be automatically started by
\fBdbus-daemon\fR(1)
whenever an application calls into the
\fIorg\&.freedesktop\&.PowerKit\fR
service\&.
.SH "AUTHOR"
.PP
Written by Ole-André Rodlie
<ole.andre.rodlie@gmail\&.com>.
.SH "BUGS"
.PP
Please send bug reports to
\m[blue]\fB\%https://github.com/rodlie/powerkit/issues\fR\m[].
.SH "SEE ALSO"
.PP
\fBpowerkit\fR(1),
\fBdbus-daemon\fR(1)
