.TH powerdwarf 1 "03 July 2018" "0.9" "powerdwarf documentation"
.SH NAME
powerdwarf -\ lightweight full featured power manager
.SH SYNOPSIS
powerdwarf [--config]
.SH DESCRIPTION
powerdwarf is a lightweight full featured power manager created for Slackware for use with alternative desktop environments and window managers, like Fluxbox, Blackbox, FVWM, WindowMaker, Openbox, Lumina and others.
.SH OPTIONS
.IP --config
Launch configuration GUI
.SH BUGS
See https://github.com/rodlie/powerdwarf/issues
.SH AUTHOR
Ole-André Rodlie (ole.andre.rodlie@gmail.com)
