.TH powerkit 1 "10 October 2018" "1.0" "powerkit documentation"
.SH NAME
powerkit -\ desktop independent full featured power manager
.SH SYNOPSIS
powerkit
.I [--config]
.SH DESCRIPTION
powerkit is an lightweight desktop independent full featured power manager, originally created for
.I Slackware
for use with alternative desktop environments and window managers, like
.I Fluxbox, Blackbox, FVWM, WindowMaker, Openbox, Lumina
and others.

.PP
.B USAGE
.PP
powerkit is an user session daemon and should be started during the X11 startup session. If your desktop environment or window manager supports XDG auto start then powerkit should automatically start, if not you will need to add powerkit to your startup file (check the documentation included with your desktop environment or window manager).

.IP
In Fluxbox add
.I powerkit &
to the
.I ~/.fluxbox/startup
file.

.IP
In Openbox add
.I powerkit &
to the
.I ~/.config/openbox/autostart
file.

.PP
.B CONFIGURATION
.PP
Click on the powerkit system tray, or run the command
.I powerkit --config
( or use
.I powerkit.desktop
) to configure powerkit.

.PP
.B SCREEN SAVER
.PP
powerkit depends on
.I XScreenSaver
to handle the screen session, the default (
.I XScreenSaver
) settings may need to be adjusted. You can launch the (
.I XScreenSaver
) configuration GUI with the
.I xscreensaver-demo
command.

.PP
Recommended settings are:

.TP
.B Mode:
.I Blank Screen Only
.TP
.B Blank After
.I 5 minutes
.TP
.B Lock Screen After:
.I enabled + 0 minutes
.PP
.B Display Power Management
(
.I enabled
):
.TP
.B Standby After:
.I 0 minutes
.TP
.B Suspend After:
.I 0 minutes
.TP
.B Off After:
.I 0 minutes
.TP
.B Quick Power-off in Blank Only Mode:
.I enabled
.PP
Note that powerkit will start
.I XScreenSaver
during startup (unless
.I org.freedesktop.ScreenSaver
is disabled).

.PP
.B BACK LIGHT
.PP
powerkit supports back light through
.I /sys/class/backlight.
The current brightness can be adjusted with the mouse wheel/touchpad scroll on the system tray icon or through the configuration GUI (bottom left slider). You can also configure brightness events in the configuration GUI.
.PP
.B NOTE!
Proper udev permissions (rules file) are required to adjust the brightness. See
.I https://github.com/rodlie/powerkit/blob/master/app/share/udev/90-backlight.rules.

.PP
.B HIBERNATE/HYBRID SLEEP
.PP
A swap partition (or file) is needed by the kernel to support hibernate/hybrid sleep. Edit the boot loader configuration and add the kernel option
.I resume=<swap_partition/swap_file>,
then save and restart.

.PP
.B REQUIREMENTS
.PP
powerkit requires
.I ConsoleKit/logind, UPower, XScreenSaver, xrandr
available during run-time.

.SH OPTIONS
.TP
.I --config
Launch configuration/status GUI.

.SH FILES
.I ~/.config/powerkit/powerkit.conf
.RS
Per user configuration file.
.RE

.SH SEE ALSO
xscreensaver(1), xscreensaver-demo(1), UPower(7)
.SH BUGS
See https://github.com/rodlie/powerkit/issues

.SH AUTHOR
Ole-André Rodlie (ole.andre.rodlie@gmail.com)

.SH COPYRIGHT
Available under the 3-clause BSD license.
